use_frameworks!

platform :ios, '9.0'

target 'MyCocoapadsLibrary_Example' do
  pod 'MyCocoapadsLibrary', :path => '../'

  target 'MyCocoapadsLibrary_Tests' do
    inherit! :search_paths

    
  end
end
